--ScrollView
local topHeight = 0
if System:iOS() then
    topHeight = window:statusBarHeight() + window:navBarHeight()
end

local scroll = ScrollView(true)
        :width(375):height(375)
        :bgColor(Color():setRGBA(255, 125, 125, 0.7))

scroll:contentSize(375 * 3, 375)

local iv = ImageView()
        :width(175):height(175)
        :contentMode(ContentMode.SCALE_TO_FILL)
        :crossSelf(CrossAxis.CENTER)
        :image("jolin")

local iv2 = ImageView()
        :width(375):height(175)
        :contentMode(ContentMode.SCALE_TO_FILL)
        :crossSelf(CrossAxis.CENTER)
        :image("jolin")

local lbl = Label()
        :width(150):height(50)
        :bgColor(Color():setRGBA(125, 255, 125, 0.7))
lbl:text("这是一段超长的文本")

local switch = Switch()
        :width(300):height(100)
        --:contentMode(ContentMode.SCALE_TO_FILL)
        :crossSelf(CrossAxis.CENTER)
switch:on(true)



scroll:addView(iv)
scroll:addView(lbl)
scroll:addView(iv2)
scroll:addView(switch)

scroll:enabled(true)
scroll:touchBeginExtension(function(x)
    print("scroll:touchBeginExtension = ", x)
end)
scroll:touchMoveExtension(function(x)
    print("scroll:touchMoveExtension = ", x)
end)
scroll:touchEndExtension(function(x)
    print("scroll:touchEndExtension = ", x)
end)
scroll:touchCancelExtension(function(x)
    print("scroll:touchCancelExtension = ", x)
end)

iv:enabled(true)
iv:touchBeginExtension(function(x)
    print("iv:touchBeginExtension = ", x)
end)
iv:touchMoveExtension(function(x)
    print("iv:touchMoveExtension = ", x)
end)
iv:touchEndExtension(function(x)
    print("iv:touchEndExtension = ", x)
end)
iv:touchCancelExtension(function(x)
    print("iv:touchCancelExtension = ", x)
end)


iv2:enabled(true)
iv2:touchBeginExtension(function(x)
    print("iv2:touchBeginExtension = ", x)
end)
iv2:touchMoveExtension(function(x)
    print("iv2:touchMoveExtension = ", x)
end)
iv2:touchEndExtension(function(x)
    print("iv2:touchEndExtension = ", x)
end)
iv2:touchCancelExtension(function(x)
    print("iv2:touchCancelExtension = ", x)
end)

lbl:enabled(true)
lbl:touchBeginExtension(function(x)
    print("lbl:touchBeginExtension = ", x)
end)
lbl:touchMoveExtension(function(x)
    print("lbl:touchMoveExtension = ", x)
end)
lbl:touchEndExtension(function(x)
    print("lbl:touchEndExtension = ", x)
end)
lbl:touchCancelExtension(function(x)
    print("lbl:touchCancelExtension = ", x)
end)

window:addView(scroll)

window:enabled(true)
window:touchBegin(function(x, y)
    print("window:touchBegin = ", x, y)
end)
window:touchMove(function(x, y)
    print("window:touchMove = ", x, y)
end)
window:touchEnd(function(x, y)
    print("window:touchEnd = ", x, y)
end)
window:touchCancel(function(x, y)
    print("window:touchCancel = ", x, y)
end)